#!/usr/bin/env bash

usage() {
cat <<EOF
usage: $(basename $0) [-h] [print] [i3blocks]
  general:
    -h, --help      print this message
    print           print the brightness
    i3blocks        use the script with i3blocks (scroll-up increases the brightness, scroll-down decreases)
EOF
}

print() {
  printf "%.0f " $(xbacklight -get)
}

i3blocks() {
  case "$BLOCK_BUTTON" in
    4)
      xbacklight -time 0 -inc 1
      ;;
    5)
      xbacklight -time 0 -dec 1
      ;;
  esac

  print
}

main() {
  if [[ -z $1 ]]
  then
    print
  else
    until [[ -z $1 ]]
    do
      case $1 in
        -h|--help )
          usage
          exit -1
          ;;
        print )
          print
          ;;
        i3blocks )
          i3blocks
          ;;
        * )
          echo "Invalid option '$1'"
          exit 1
          ;;
      esac
      shift
    done
  fi
}

main $@
