#!/usr/bin/env bash

usage() {
cat <<EOF
usage: $(basename $0) [-h] [up %] [down %] [show]
  general:
    -h, --help      print this message
    up              increase the brightness by the given %
    down            decrease the brightness by the given %
    show            print the brightness
EOF
}

up() {
  light -A ${1:-"1"}
}

down() {
  light -U ${1:-"1"}
}

show() {
  printf "%.0f " $(light -G)
}

main() {
  if [[ -z $1 ]]
  then
    usage
  else
    until [[ -z $1 ]]
    do
      case $1 in
        -h|--help )
	    usage
	    exit -1
            ;;
	up )
	    shift
            up $1
            ;;
	down )
	    shift
            down $1
	    ;;
	show )
	    show
	    ;;
        * )
            echo "Invalid option '$1'"
            exit 1
            ;;
      	esac
      shift
    done
  fi
}

main $@
