#!/usr/bin/env bash

usage() {
cat <<EOF
usage: $(basename $0) [-h] [up %] [down %] [print] [i3blocks]
  general:
    -h, --help      print this message
    up              increase the brightness by the given %
    down            decrease the brightness by the given %
    print           print the brightness
    i3blocks        use the script with i3blocks (scroll-up increases the brightness, scroll-down decreases)
EOF
}

up() {
  light -A ${1:-"1"}
}

down() {
  light -U ${1:-"1"}
}

print() {
  printf "%.0f " $(light -G)
}

i3blocks() {
  case "$BLOCK_BUTTON" in
    4)
      up
      ;;
    5)
      down
      ;;
  esac

  print
}

main() {
  if [[ -z $1 ]]
  then
    print
  else
    until [[ -z $1 ]]
    do
      case $1 in
        -h|--help )
          usage
          exit -1
          ;;
	up )
	  shift
	  up $1
	  ;;
	down )
	  shift
	  down $1
	  ;;
        print )
          print
          ;;
        i3blocks )
          i3blocks
          ;;
        * )
          echo "Invalid option '$1'"
          exit 1
          ;;
      esac
      shift
    done
  fi
}

main $@
