#!/usr/bin/env bash

set -e

# rofi settings
PROMPT="Power:"
WIDTH=25
BORDER_WIDTH=0
PADDING=50
LOCATION=0
BORDER_COLOR=#282828
BACKGROUD_COLOR=#282828
FOREGROUND_COLOR=#ebdbb2
HIGHLIGHTED_BACKGROUND_COLOR=#ebdbb2
HIGHLIGHTED_FOREGROUND_COLOR=#282828

LOCK_SCRIPT="${HOME}/.config/i3lock/lock.sh"

declare -a menu

menu=(
  Shutdown
  Reboot
  Hibernate
  Suspend
  Logout
  Lock
  Cancel
)

menu_nrows=${#menu[@]}

usage() {
cat <<EOF
usage: $(basename $0) [-h] [-p prompt] [-w width] [-bw border-width] [-padding padding]
                      [-l location] [-bc border-color] [-bg background-color] [-fg foreground-color]
                      [-hlbg highlighted-background-color] [-hlfg highlighted-foreground-color]
                      [-lock-script lock-script]
  general:
    -h, --help        print this message.
    -p, --prompt      the text to use in the menu
    -w, --width       the width of the menu
    -bw               the border width of the menu
    -padding          the padding of the menu
    -l, --location    the location of the menu on the screen:
                        1 2 3
                        8 0 4
                        7 6 5
    -bc               the border color of the menu
    -bg               the background color of the menu
    -fg               the foreground color of the menu
    -hlbg             the background color of the highlighted item
    -hlfg             the foreground color of the highlighted item
    -lock-script      the lock-script to use
EOF
}

rofi_command() {
cat <<-EOF
  rofi \
    -dmenu \
    -i \
    -lines $menu_nrows \
    -p $PROMPT \
    -width $WIDTH \
    -bw $BORDER_WIDTH \
    -padding $PADDING \
    -location $LOCATION \
    -separator-style none \
    -hide-scrollbar \
    -bc "${BORDER_COLOR}" \
    -bg "${BACKGROUD_COLOR}" \
    -fg "${FOREGROUND_COLOR}" \
    -hlbg "${HIGHLIGHTED_BACKGROUND_COLOR}" \
    -hlfg "${HIGHLIGHTED_FOREGROUND_COLOR}"
EOF
}

process_selection() {
  case "$1" in
    Shutdown  )
      i3-msg -q "exec systemctl poweroff"
      ;;
    Reboot  )
      i3-msg -q "exec systemctl reboot"
      ;;
    Hibernate )
      i3-msg -q "exec systemctl hibernate"
      ;;
    Suspend )
      i3-msg -q "exec systemctl suspend"
      ;;
    Logout  )
      i3-msg exit
      ;;
    Lock  )
      i3-msg -q "exec $LOCK_SCRIPT"
      ;;
    * )
      ;;
    esac
}

show_menu() {
  selection=$(printf '%s\n' "${menu[@]}" | $(rofi_command))
  process_selection $selection
}

main() {
  until [[ -z $1 ]]
  do
    case $1 in
      -h|--help )
        usage
        exit 0
        ;;
      -p|--prompt )
        shift
        PROMPT=$1
        ;;
      -w|--width  )
        shift
        WIDTH=$1
        ;;
      -bw )
        shift
        BORDER_WIDTH=$1
        ;;
      -padding  )
        shift
        PADDING=$1
        ;;
      -l|--location )
        shift
        LOCATION=$1
        ;;
      -bc )
        shift
        BORDER_COLOR=$1
        ;;
      -bg )
        shift
        BACKGROUD_COLOR=$1
        ;;
      -fg )
        shift
        FOREGROUND_COLOR=$1
        ;;
      -hlbg )
        shift
        HIGHLIGHTED_BACKGROUND_COLOR=$1
        ;;
      -hlfg )
        shift
        HIGHLIGHTED_FOREGROUND_COLOR=$1
        ;;
      * )
        echo "Invalid option '$1'"
        exit 1
        ;;
    esac
    shift
  done

  show_menu
}

main $@
