#!/usr/bin/env bash

# Based on a script by:
# Julien Bonjean <julien@bonjean.info>
# Alexander Keller <github@nycroth.com>

MIXER=
SCONTROL=

usage() {
cat <<EOF
usage: $(basename $0) [-h] [-m mixer] [-c control] [toggle] [up %] [down %] [show]
  general:
    -h, --help      print this message
    -m, --mixer     sets the mixer to use (default='default')
    -c, --control   sets the control to use (default='Master')
    toggle          toggles between mute and unmute
    up              increase the volume by the given %
    down            decrease the volume by the given %
    show           print the volume
EOF
}

get_mixer() {
  if [ -z $MIXER ]
  then
    if [ -n "$(lsmod | grep pulse)" ]
    then
      MIXER="pulse"
    elif [ -n "$(lsmod | grep jack)" ]
    then
      MIXER="jackplug"
    else
      MIXER="default"
    fi
  fi

  echo $MIXER
}

get_scontrol() {
  if [ -z $SCONTROL ]
  then
    local mixer=$(get_mixer)
    SCONTROL=$(amixer -D $mixer scontrols | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" | head -n1)
  fi

  echo $SCONTROL
}

get_capability() {
  amixer -D $(get_mixer) get $(get_scontrol) | sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

get_volume() {
  amixer -D $(get_mixer) get $(get_scontrol) $(get_capability) | grep -o "\[.*%\]" | grep -o "[0-9]*" | head -n1
}

is_muted() {
  amixer -D $(get_mixer) get $(get_scontrol) | grep -q "\[off\]"
}

toggle() {
  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability) toggle
}

up() {
  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability)  ${1:-"5"}%+ unmute
}

down() {
  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability)  ${1:-"5"}%- unmute
}

show() {
  local volume=$(get_volume)
  
  if [ "$volume" -eq 0 ] || is_muted
  then
    output="muted"
  else
    output="$volume%"
  fi

  echo $output
}

main() {
  if [[ -z $1 ]]
  then
    usage
  else
    until [[ -z $1 ]]
    do
      case $1 in
        -h|--help )
          usage
          exit -1
          ;;
        -m|--mixer )
          shift
          MIXER=$1
          ;;
        -c|--control )
          shift
          SCONTROL=$1
          ;;
        toggle )
          toggle
          ;;
        up )
          shift
          up $1
          ;;
        down )
          shift
          down $1
          ;;
        show )
          show
          ;;
        * )
          echo "Invalid option '$1'"
          exit 1
          ;;
      esac
      shift
    done
  fi
}

main $@
