#!/usr/bin/env bash

# Based on a script by:
# Julien Bonjean <julien@bonjean.info>
# Alexander Keller <github@nycroth.com>

AUDIO_HIGH_SYMBOL=''
AUDIO_LOW_SYMBOL=''
AUDIO_MUTED_SYMBOL=''

MIXER=
SCONTROL=

usage() {
cat <<EOF
usage: $(basename $0) [-h] [-m mixer] [-c control] [toggle] [up %] [down %] [print] [i3blocks]
  general:
    -h, --help      print this message
    -m, --mixer     sets the mixer to use (default='default')
    -c, --control   sets the control to use (default='Master')
    toggle          toggles between mute and unmute
    up              increase the volume by the given %
    down            decrease the volume by the given %
    print           print the volume in a fancy format
    i3blocks        use the script with i3blocks (left-click opens pavu-control, right-click will toggle the volume,
                    scroll up will increase it, scroll down will decrease it)
EOF
}

get_mixer() {
  if [ -z $MIXER ]
  then
    if [ -n "$(lsmod | grep pulse)" ]
    then
      MIXER="pulse"
    elif [ -n "$(lsmod | grep jack)" ]
    then
      MIXER="jackplug"
    else
      MIXER="default"
    fi
  fi

  echo $MIXER
}

get_scontrol() {
  if [ -z $SCONTROL ]
  then
    local mixer=$(get_mixer)
    SCONTROL=$(amixer -D $mixer scontrols | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" | head -n1)
  fi

  echo $SCONTROL
}

get_capability() {
  amixer -D $(get_mixer) get $(get_scontrol) | sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

get_volume() {
  amixer -D $(get_mixer) get $(get_scontrol) $(get_capability) | grep -o "\[.*%\]" | grep -o "[0-9]*" | head -n1
}

is_muted() {
  amixer -D $(get_mixer) get $(get_scontrol) | grep -q "\[off\]"
}

toggle() {
  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability) toggle
}

up() {
  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability)  ${1:-"5"}%+ unmute
}

down() {
  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability)  ${1:-"5"}%- unmute
}

icon() {
  local volume=$(get_volume)
  if [ "$volume" -le 25 ] || is_muted
  then
    echo $AUDIO_MUTED_SYMBOL
  elif [ "$volume" -le 50 ]
  then
    echo $AUDIO_LOW_SYMBOL
  else
    echo $AUDIO_HIGH_SYMBOL
  fi
}

print() {
  local volume=$(get_volume)
  local output=$(icon)
  if [ "$volume" -eq 0 ] || is_muted
  then
    output="$output muted"
  else
    output="$output $volume%"
  fi

  echo $output
}

i3blocks() {
  case "$BLOCK_BUTTON" in
    1)
      pavucontrol -t 3
      ;;
    3)
      toggle
      ;;
    4)
      up 5
      ;;
    5)
      down 5
      ;;
  esac

  print
}

main() {
  if [[ -z $1 ]]
  then
    print
  else
    until [[ -z $1 ]]
    do
      case $1 in
        -h|--help )
          usage
          exit -1
          ;;
        -m|--mixer )
          shift
          MIXER=$1
          ;;
        -c|--control )
          shift
          SCONTROL=$1
          ;;
        toggle )
          toggle
          ;;
        up )
          shift
          up $1
          ;;
        down )
          shift
          down $1
          ;;
        print )
          print
          ;;
        i3blocks )
          i3blocks
          ;;
        * )
          echo "Invalid option '$1'"
          exit 1
          ;;
      esac
      shift
    done
  fi
}

main $@
