#!/usr/bin/env bash

usage() {
cat <<EOF
usage: $(basename $0) [-h] [print] [i3blocks]
  general:
    -h, --help      print this message
    print           print the status in a fancy format
    i3blocks        use the script with i3blocks (left-click opens nmtui, right click toggles the radio on and off)
EOF
}

status() {
  echo $(nmcli radio wifi)
}

print() {
  echo $(status)
}

i3blocks() {
  case "$BLOCK_BUTTON" in
    1)
      termite --name "__nmtui__" -e nmtui
      ;;
    3)
      if [[ $(status) == "enabled" ]]
      then
        nmcli radio wifi off
      else
        nmcli radio wifi on
      fi
      ;;
  esac

  print
}

main() {
  if [[ -z $1 ]]
  then
    print
  else
    until [[ -z $1 ]]
    do
      case $1 in
        -h|--help )
          usage
          exit -1
          ;;
        print )
          print
          ;;
        i3blocks )
          i3blocks
          ;;
        * )
          echo "Invalid option '$1'"
          exit 1
          ;;
      esac
      shift
    done
  fi
}

main $@
